import json
import time

new_data_str = """[
    {
        "domain": ".bilibili.tv",
        "expirationDate": 1794224583.414238,
        "hostOnly": false,
        "httpOnly": false,
        "name": "bili_jct",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "7f0dc895d62741c9dbacdf4ab5d6cfe6"
    },
    {
        "domain": ".bilibili.tv",
        "expirationDate": 1794224583.414441,
        "hostOnly": false,
        "httpOnly": false,
        "name": "DedeUserID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1720622913"
    },
    {
        "domain": ".bilibili.tv",
        "expirationDate": 1807335255.786043,
        "hostOnly": false,
        "httpOnly": false,
        "name": "buvid4",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "96FA11B7-CCCF-F978-6529-3FE2D155844555037-026030613-KxldrlM0Q3OXWNHXWqAvzA%3D%3D"
    },
    {
        "domain": ".bilibili.tv",
        "expirationDate": 1784721202.804942,
        "hostOnly": false,
        "httpOnly": false,
        "name": "buvid3",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "3c105506-1303-470e-8484-60a8a2341c1652524infoc"
    },
    {
        "domain": "www.bilibili.tv",
        "expirationDate": 1794224552,
        "hostOnly": true,
        "httpOnly": false,
        "name": "g_state",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "{\\"i_l\\":0,\\"i_ll\\":1778672552550,\\"i_b\\":\\"r697yMVYfyQWZwEE4bYuccOqF9Z3EVD2s6alef49MyY\\",\\"i_e\\":{\\"enable_itp_optimization\\":0},\\"i_et\\":1778672552546}"
    },
    {
        "domain": ".bilibili.tv",
        "expirationDate": 1781284256.832285,
        "hostOnly": false,
        "httpOnly": false,
        "name": "bstar-web-lang",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "vi"
    },
    {
        "domain": ".bilibili.tv",
        "expirationDate": 1794224583.41453,
        "hostOnly": false,
        "httpOnly": false,
        "name": "DedeUserID__ckMd5",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "b1013a47b54f58f422f68eae01a7aa1d"
    },
    {
        "domain": ".bilibili.tv",
        "expirationDate": 1794224583.41435,
        "hostOnly": false,
        "httpOnly": false,
        "name": "joy_jct",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "7f0dc895d62741c9dbacdf4ab5d6cfe6"
    },
    {
        "domain": ".bilibili.tv",
        "expirationDate": 1794224583.414617,
        "hostOnly": false,
        "httpOnly": false,
        "name": "mid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1720622913"
    },
    {
        "domain": ".bilibili.tv",
        "expirationDate": 1794224583.414039,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SESSDATA",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "12dc8952%2C1794224583%2C13124%2A510041"
    }
]"""

netscape_file = r'e:\taimoithu\backend\backend\cookies.txt'

try:
    with open(netscape_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()
except FileNotFoundError:
    lines = ["# Netscape HTTP Cookie File\n# This file is generated by yt-dlp.  Do not edit.\n\n"]

# Remove all bilibili.tv cookies
filtered_lines = []
for line in lines:
    if "bilibili.tv" not in line:
        filtered_lines.append(line)

new_cookies = json.loads(new_data_str)

for c in new_cookies:
    domain = c.get('domain', '')
    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
    path = c.get('path', '/')
    secure = "TRUE" if c.get('secure', False) else "FALSE"
    expiration = str(int(c.get('expirationDate', 0)))
    name = c.get('name', '')
    value = c.get('value', '')
    
    line = f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n"
    filtered_lines.append(line)

with open(netscape_file, 'w', encoding='utf-8') as f:
    f.writelines(filtered_lines)

print("Netscape cookies updated successfully.")
